version: "2"
services:
    lualatex:
        image: vertisfinance/lualatex
        hostname: lualatex
        volumes:
            - .:/var/lib/data
        entrypoint: ["python3", "entry.py"]
        stop_signal: SIGINT
        environment:
            USER_NAME: example-user
            USER_ID: 1000
        command: start
